### ISSUE TITLE
[Feature Request] Remove individual torrent method?

### ISSUE THREAD

**Issue by mirceaciu** [masterwok/simple-torrent-android#5]
I can't seem to find a method to remove/stop downloaded torrents. I see that libtorrent manual has such a method. 

```
void remove_torrent(torrent_handle const& h, int options = none);
```

I don't know much about this dependencies or Java in general, but could it be that the method is available on this [session instance](https://github.com/masterwok/simple-torrent-android/blob/master/simpletorrentandroid/src/main/java/com/masterwok/simpletorrentandroid/TorrentSession.kt#L40)?

**Comment by masterwok** [comment]
_TorrentSession_ has a stop method, [here](https://github.com/masterwok/simple-torrent-android/blob/9fa6ad7d0ddc6b4482844fa55b323f5d9a0b51ef/simpletorrentandroid/src/main/java/com/masterwok/simpletorrentandroid/TorrentSession.kt#L457). It invokes stop on the session manager and removes the event listener. 

I didn't include a method on the _TorrentSession_ to call remove on the _SessionManager_ method, [here](https://github.com/frostwire/frostwire-jlibtorrent/blob/a29249a940d34aba8c4677d238b472ef01833506/src/main/java/com/frostwire/jlibtorrent/SessionManager.java#L568). This was because for my use case, I invoke the stop method and then remove the file/directory from the download location.

**Comment by masterwok** [comment]
I will add this once I find some time to get around to it.

**Comment by mirceaciu** [comment]
Ah Ok!. I only use magnet links so if I stop the TorrentSession then the magnet will not be there when a new session is instanced, right? No need for a remove torrent method, I could just stop then start a new session

**Comment by masterwok** [comment]
Yes, if you create a new TorrentSession instance, then the new instance will not know anything about the previous session. Does that answer your question?

**Comment by mirceaciu** [comment]
Yes it does. Thank you!

**Comment by masterwok** [comment]
Awesome, thanks. Going to close this ticket.
